-- CreateTable
CREATE TABLE "FamilyRecord" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "mandalName" TEXT NOT NULL,
    "villageName" TEXT NOT NULL,
    "rationCard" TEXT,
    "voterCard" TEXT,
    "name" TEXT NOT NULL,
    "numFamilyPersons" INTEGER NOT NULL,
    "address" TEXT NOT NULL,
    "phoneNumber" TEXT NOT NULL,
    "aadhar" TEXT,
    "gender" TEXT NOT NULL,
    "dateOfBirth" DATETIME,
    "qualification" TEXT,
    "caste" TEXT,
    "subCaste" TEXT,
    "occupation" TEXT,
    "needEmployment" TEXT,
    "arogyasriCardNumber" TEXT,
    "shgMember" TEXT,
    "schemesEligible" TEXT,
    "remarks" TEXT,
    "birthdayThisWeek" BOOLEAN NOT NULL DEFAULT false,
    "birthdayThisMonth" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
